package com.example.otomotuzplus.ui.models

data class AppStrings(
    val home: String,
    val search: String,
    val add: String,
    val favorites: String,
    val profile: String,
    val searchPlaceholder: String,
    val buy: String,
    val sell: String,
    val findCar: String,
    val listYourCar: String,
    val popularBrands: String,
    val seeAll: String,
    val freshArrivals: String,
    val featured: String,
    val filters: String,
    val sortBy: String,
    val sortNameAsc: String,
    val sortNameDesc: String,
    val sortPriceAsc: String,
    val sortPriceDesc: String,
    val sortYearDesc: String,
    val sortMileageAsc: String,
    val brand: String,
    val model: String,
    val minPrice: String,
    val maxPrice: String,
    val minYear: String,
    val maxYear: String,
    val maxMileage: String,
    val fuelType: String,
    val fuelPetrol: String,
    val fuelDiesel: String,
    val fuelHybrid: String,
    val fuelElectric: String,
    val transmission: String,
    val transmissionAutomatic: String,
    val transmissionManual: String,
    val bodyType: String,
    val bodySedan: String,
    val bodySuv: String,
    val bodyCoupe: String,
    val bodyHatchback: String,
    val bodyWagon: String,
    val driveType: String,
    val driveFwd: String,
    val driveRwd: String,
    val driveAwd: String,
    val drive4x4: String,
    val condition: String,
    val conditionNew: String,
    val conditionUsed: String,
    val location: String,
    val resetFilters: String,
    val resultsCount: String,
    val noSearchResults: String,
    val myListings: String,
    val history: String,
    val settings: String,
    val logout: String,
    val theme: String,
    val themeSystem: String,
    val themeLight: String,
    val themeDark: String,
    val language: String,
    val notifications: String,
    val appPreferences: String,
    val noHistory: String,
    val memberSince: String,
    val chooseLanguage: String,
    val chooseTheme: String,
    val listingsStatus: String,
    val historyEmpty: String,
    val brandLogosPlaceholder: String,
    val noListingsYet: String,
    val verifiedListing: String,
    val seller: String,
    val back: String,
    val yearProduction: String,
    val mileage: String,
    val fuel: String,
    val gearbox: String,
    val engineCapacityLabel: String,
    val power: String,
    val unitCurrency: String,
    val unitKm: String,
    val unitCm3: String,
    val unitPower: String,
    val addListingTitle: String,
    val brandAndModel: String,
    val price: String,
    val year: String,
    val city: String,
    val addPhotos: String,
    val photoSourceTitle: String,
    val photoSourceMessage: String,
    val photoSourceGallery: String,
    val photoSourceCamera: String,
    val selectedPhotoContentDescription: String,
    val removePhotoContentDescription: String,
    val addListingSuccess: String,
    val addListingError: String,
    val addListingRequiredFields: String,
    val uploading: String,
    val noEmail: String
)

val PolishStrings = AppStrings(
    home = "Start",
    search = "Szukaj",
    add = "Dodaj",
    favorites = "Ulubione",
    profile = "Profil",
    searchPlaceholder = "Szukaj samochodów, marek lub modeli",
    buy = "Kup",
    sell = "Sprzedaj",
    findCar = "Znajdź auto",
    listYourCar = "Dodaj ogłoszenie",
    popularBrands = "Popularne marki",
    seeAll = "Zobacz wszystko",
    freshArrivals = "Najnowsze oferty",
    featured = "Wyróżnione",
    filters = "Filtry",
    sortBy = "Sortuj",
    sortNameAsc = "Nazwa A-Z",
    sortNameDesc = "Nazwa Z-A",
    sortPriceAsc = "Cena rosnąco",
    sortPriceDesc = "Cena malejąco",
    sortYearDesc = "Rok od najnowszych",
    sortMileageAsc = "Przebieg rosnąco",
    brand = "Marka",
    model = "Model",
    minPrice = "Cena od",
    maxPrice = "Cena do",
    minYear = "Rok od",
    maxYear = "Rok do",
    maxMileage = "Maks. przebieg (km)",
    fuelType = "Rodzaj paliwa",
    fuelPetrol = "Benzyna",
    fuelDiesel = "Diesel",
    fuelHybrid = "Hybryda",
    fuelElectric = "Elektryczny",
    transmission = "Skrzynia biegów",
    transmissionAutomatic = "Automatyczna",
    transmissionManual = "Manualna",
    bodyType = "Typ nadwozia",
    bodySedan = "Sedan",
    bodySuv = "SUV",
    bodyCoupe = "Coupe",
    bodyHatchback = "Hatchback",
    bodyWagon = "Kombi",
    driveType = "Napęd",
    driveFwd = "Przedni (FWD)",
    driveRwd = "Tylny (RWD)",
    driveAwd = "Na wszystkie koła (AWD)",
    drive4x4 = "4x4",
    condition = "Stan",
    conditionNew = "Nowy",
    conditionUsed = "Używany",
    location = "Lokalizacja",
    resetFilters = "Wyczyść",
    resultsCount = "Wyniki: %d",
    noSearchResults = "Brak ofert spełniających kryteria.",
    myListings = "Moje ogłoszenia",
    history = "Historia",
    settings = "Ustawienia",
    logout = "Wyloguj się",
    theme = "Motyw",
    themeSystem = "Systemowy",
    themeLight = "Jasny",
    themeDark = "Ciemny",
    language = "Język",
    notifications = "Powiadomienia",
    appPreferences = "Preferencje aplikacji",
    noHistory = "Brak historii",
    memberSince = "Członek od %s",
    chooseLanguage = "Wybierz język",
    chooseTheme = "Wybierz motyw",
    listingsStatus = "Aktywne",
    historyEmpty = "Brak historii",
    brandLogosPlaceholder = "kiedyś zamienimy je",
    noListingsYet = "Nie dodałeś jeszcze żadnych ogłoszeń.",
    verifiedListing = "Zweryfikowane ogłoszenie",
    seller = "Sprzedający",
    back = "Wróć",
    yearProduction = "Rok produkcji",
    mileage = "Przebieg",
    fuel = "Paliwo",
    gearbox = "Skrzynia",
    engineCapacityLabel = "Pojemność",
    power = "Moc",
    unitCurrency = "zł",
    unitKm = "km",
    unitCm3 = "cm3",
    unitPower = "KM",
    addListingTitle = "Dodaj ogłoszenie",
    brandAndModel = "Marka i model",
    price = "Cena",
    year = "Rocznik",
    city = "Miasto",
    addPhotos = "Dodaj zdjęcia",
    photoSourceTitle = "Wybierz źródło zdjęcia",
    photoSourceMessage = "Skąd chcesz dodać zdjęcia do swojego ogłoszenia?",
    photoSourceGallery = "Galeria",
    photoSourceCamera = "Aparat",
    selectedPhotoContentDescription = "Wybrane zdjęcie",
    removePhotoContentDescription = "Usuń zdjęcie",
    addListingSuccess = "Ogłoszenie dodane!",
    addListingError = "Błąd: %s",
    addListingRequiredFields = "Podaj przynajmniej markę i cenę!",
    uploading = "Wysyłanie...",
    noEmail = "brak emaila"
)

val EnglishStrings = AppStrings(
    home = "Home",
    search = "Search",
    add = "Add",
    favorites = "Favorites",
    profile = "Profile",
    searchPlaceholder = "Search cars, brands, or models",
    buy = "Buy",
    sell = "Sell",
    findCar = "Find a Car",
    listYourCar = "List Your Car",
    popularBrands = "Popular Brands",
    seeAll = "See All",
    freshArrivals = "Fresh Arrivals",
    featured = "FEATURED",
    filters = "Filters",
    sortBy = "Sort by",
    sortNameAsc = "Name A-Z",
    sortNameDesc = "Name Z-A",
    sortPriceAsc = "Price low to high",
    sortPriceDesc = "Price high to low",
    sortYearDesc = "Newest year",
    sortMileageAsc = "Mileage low to high",
    brand = "Brand",
    model = "Model",
    minPrice = "Min price",
    maxPrice = "Max price",
    minYear = "Min year",
    maxYear = "Max year",
    maxMileage = "Max mileage (km)",
    fuelType = "Fuel type",
    fuelPetrol = "Petrol",
    fuelDiesel = "Diesel",
    fuelHybrid = "Hybrid",
    fuelElectric = "Electric",
    transmission = "Transmission",
    transmissionAutomatic = "Automatic",
    transmissionManual = "Manual",
    bodyType = "Body type",
    bodySedan = "Sedan",
    bodySuv = "SUV",
    bodyCoupe = "Coupe",
    bodyHatchback = "Hatchback",
    bodyWagon = "Wagon",
    driveType = "Drive type",
    driveFwd = "Front-wheel drive (FWD)",
    driveRwd = "Rear-wheel drive (RWD)",
    driveAwd = "All-wheel drive (AWD)",
    drive4x4 = "4x4",
    condition = "Condition",
    conditionNew = "New",
    conditionUsed = "Used",
    location = "Location",
    resetFilters = "Reset",
    resultsCount = "Results: %d",
    noSearchResults = "No offers match your criteria.",
    myListings = "My listings",
    history = "History",
    settings = "Settings",
    logout = "Logout",
    theme = "Theme",
    themeSystem = "System",
    themeLight = "Light",
    themeDark = "Dark",
    language = "Language",
    notifications = "Notifications",
    appPreferences = "App preferences",
    noHistory = "No history",
    memberSince = "Member since %s",
    chooseLanguage = "Choose language",
    chooseTheme = "Choose theme",
    listingsStatus = "Active",
    historyEmpty = "No history found",
    brandLogosPlaceholder = "we will replace them later",
    noListingsYet = "You have not added any listings yet.",
    verifiedListing = "Verified listing",
    seller = "Seller",
    back = "Back",
    yearProduction = "Year of production",
    mileage = "Mileage",
    fuel = "Fuel",
    gearbox = "Gearbox",
    engineCapacityLabel = "Engine capacity",
    power = "Power",
    unitCurrency = "PLN",
    unitKm = "km",
    unitCm3 = "cm3",
    unitPower = "HP",
    addListingTitle = "Add listing",
    brandAndModel = "Brand and model",
    price = "Price",
    year = "Year",
    city = "City",
    addPhotos = "Add photos",
    photoSourceTitle = "Choose photo source",
    photoSourceMessage = "Where do you want to add photos for your listing from?",
    photoSourceGallery = "Gallery",
    photoSourceCamera = "Camera",
    selectedPhotoContentDescription = "Selected photo",
    removePhotoContentDescription = "Remove photo",
    addListingSuccess = "Listing added!",
    addListingError = "Error: %s",
    addListingRequiredFields = "Provide at least brand and price!",
    uploading = "Uploading...",
    noEmail = "no email"
)
