package com.example.otomotuzplus.ui.models

data class AppStrings(
    val home: String,
    val search: String,
    val add: String,
    val favorites: String,
    val profile: String,
    val myListings: String,
    val history: String,
    val settings: String,
    val logout: String,
    val theme: String,
    val themeSystem: String,
    val themeLight: String,
    val themeDark: String,
    val language: String,
    val notifications: String,
    val appPreferences: String,
    val noHistory: String,
    val memberSince: String,
    val chooseLanguage: String,
    val chooseTheme: String,
    val listingsStatus: String,
    val historyEmpty: String
)

val PolishStrings = AppStrings(
    home = "Start",
    search = "Szukaj",
    add = "Dodaj",
    favorites = "Ulubione",
    profile = "Profil",
    myListings = "Moje ogłoszenia",
    history = "Historia",
    settings = "Ustawienia",
    logout = "Wyloguj się",
    theme = "Motyw",
    themeSystem = "Systemowy",
    themeLight = "Jasny",
    themeDark = "Ciemny",
    language = "Język",
    notifications = "Powiadomienia",
    appPreferences = "Preferencje aplikacji",
    noHistory = "Brak historii",
    memberSince = "Członek od %s",
    chooseLanguage = "Wybierz język",
    chooseTheme = "Wybierz motyw",
    listingsStatus = "Aktywne",
    historyEmpty = "Brak historii"
)

val EnglishStrings = AppStrings(
    home = "Home",
    search = "Search",
    add = "Add",
    favorites = "Favorites",
    profile = "Profile",
    myListings = "My listings",
    history = "History",
    settings = "Settings",
    logout = "Logout",
    theme = "Theme",
    themeSystem = "System",
    themeLight = "Light",
    themeDark = "Dark",
    language = "Language",
    notifications = "Notifications",
    appPreferences = "App preferences",
    noHistory = "No history",
    memberSince = "Member since %s",
    chooseLanguage = "Choose language",
    chooseTheme = "Choose theme",
    listingsStatus = "Active",
    historyEmpty = "No history found"
)
